layout_spectrum: 0.8619764
typography_spectrum: 1
color:
  saturation: 0.7981905
  lightness: 0.7162296
  brandStrength: 0.8339546
  rhythmicContrast: 0.2010923
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: HannaJoyKitchen
